{
 "title": "Zugstats",
 "description": "Zugstats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Smooth", "label": "2m", "query": "2m" }
  ]
 },
 "panels": [
  { "title": "Unifi and pihole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (unpoller_device_uplink_latency_seconds{name=\"<NETWORK_DEVICE_NAME>\"})",
     "legendFormat": "{{name}} Uplink Latency"
    }
   ]
  },
  {
   "title": "WAN Throughput",
   "type": "stat",
   "description": "Spikes on this graph that are missing from the LAN graph indicate gateway-originated traffic, like a scheduled speed test. Rx is on the negative axis.",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(unpoller_device_wan_receive_bytes_total{}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Rx"
    },
    {
     "expr": "rate(unpoller_device_wan_transmit_bytes_total{}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Tx"
    }
   ]
  },
  {
   "title": "Client Bandwidth - Receive (Top 5)",
   "type": "timeseries",
   "description": "Client Bandwidth - Receive (Top 5)",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, sum by (name) (rate(unpoller_client_transmit_bytes_total{}[$__interval])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client Bandwidth - Transmit (Top 5)",
   "type": "timeseries",
   "description": "Client Bandwidth - Transmit ",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, sum by (name) (rate(unpoller_client_receive_bytes_total{}[$__interval])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pihole Filtering",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pihole_status", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "DNS Queries Per Minute - By Top Sources",
   "type": "stat",
   "description": "DNS Queries Per Minute - By Top Sources",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          increase(pihole_top_sources{source!=\"127.0.0.1\", source!=\"<DEVICE_IP_1>\"}[1m]),\n          \"source\",\n          \"<DEVICE_NAME_1>\",\n          \"source\",\n          \"<DEVICE_IP_2>\"\n        ),\n        \"source\",\n        \"<DEVICE_NAME_2>\",\n        \"source\",\n        \"<DEVICE_IP_3>\"\n      ),\n      \"source\",\n      \"<DEVICE_NAME_3>\",\n      \"source\",\n      \"<DEVICE_IP_4>\"\n    ),\n    \"source\",\n    \"<DEVICE_NAME_4>\",\n    \"source\",\n    \"<DEVICE_IP_5>\"\n  )\n)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  { "title": "Flume Water Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "House Daily Water Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  flume_daily_total_water_usage_gallons{device_id=\"<FLUME_DEVICE_ID>\"},\r\n  \"date\",\r\n  \"$2/$3\",\r\n  \"date\",\r\n  \"(\\\\d{4})-(\\\\d{2})-(\\\\d{2})\"\r\n)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "Water Running History Gallons Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flume_current_flow_rate_gallons_per_minute{device_name=\"<FLUME_DEVICE_ID>\"}",
     "legendFormat": "House"
    }
   ]
  },
  {
   "title": "Water Running GPM",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flume_current_flow_rate_gallons_per_minute{device_name=\"<FLUME_DEVICE_ID>\"}",
     "legendFormat": "House"
    }
   ]
  },
  {
   "title": "Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {}
   ]
  },
  { "title": "<GAMING_PC_NAME>", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Utilization History",
   "type": "timeseries",
   "description": "Utilization History",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_type=\"Load\", sensor_name=~\"GPU Core\"}",
     "legendFormat": "{{sensor_name}}"
    },
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_type=\"Load\", sensor_name=\"CPU Total\"}",
     "legendFormat": "{{sensor_name}}"
    },
    {
     "expr": "(librehardwaremonitor_sensor_value{sensor_name=\"Memory Used\"} / 64) * 100",
     "legendFormat": "System Memory"
    },
    {
     "expr": "(librehardwaremonitor_sensor_value{sensor_name=\"GPU Memory Used\"} / 16000) * 100",
     "legendFormat": "GPU Memory"
    }
   ]
  },
  {
   "title": "System Memory Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_type=\"Data\",sensor_name=\"Memory Used\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_name=\"GPU Memory Used\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_type=\"Power\", sensor_name=\"GPU Package\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "CPU Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(librehardwaremonitor_sensor_value{sensor_type=\"Power\", sensor_name=\"Package\"})",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "GPU Core Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_type=\"Load\", sensor_name=\"GPU Core\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "CPU Core Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_type=\"Load\", sensor_name=\"CPU Total\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "SSD Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_name=\"Total Activity\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "CPU Core Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_name=\"Core (Tctl/Tdie)\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "SSD Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_name=\"Temperature\", sensor_id=\"/nvme/0/temperature/0\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "GPU Core Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librehardwaremonitor_sensor_value{sensor_type=\"Temperature\", sensor_name=\"GPU Core\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  }
 ]
}